from __future__ import annotations

import re
from typing import Optional


# V6.0 was intentionally authored with English operational labels.  The
# production repository, however, uses Chinese reports.  Keep the underlying
# JSON/schema field names stable and localise only the human-facing Markdown.
_TEXT_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("## 1. Market Pulse", "## 1. 市场脉搏"),
    ("## 2. Significant Changes", "## 2. 重要变化"),
    ("## 3. Opportunity Ranking", "## 3. 机会排名"),
    ("## 4. Setup Cards", "## 4. 交易计划卡"),
    ("## 5. LLM Health", "## 5. 大模型健康度"),
    ("## 6. Prediction Scoreboard", "## 6. 预测验证看板"),
    ("## 7. Free Public Data Context", "## 7. 免费公共数据"),
    ("## 8. Run Health", "## 8. 运行健康度"),
    ("## Methodology", "## 方法说明"),
    ("### Macro snapshot", "### 宏观快照"),
    ("### Recent SEC filings", "### 近期 SEC 文件"),
    ("Regime:", "市场状态:"),
    ("Breadth:", "市场广度:"),
    ("Average Opportunity:", "平均机会分:"),
    ("Average Risk:", "平均风险分:"),
    ("Evidence Coverage:", "证据覆盖率:"),
    ("Opportunity / Quality / Risk:", "机会 / 质量 / 风险:"),
    ("Forecast Score:", "预测评分:"),
    ("Factors:", "因子:"),
    ("Entry:", "入场区间:"),
    ("Stop:", "止损:"),
    ("Targets:", "目标位:"),
    ("R:R:", "风险收益比:"),
    ("Qualitative catalysts (LLM extracted, not numerically scored):", "定性利好催化（由 LLM 提取，不参与数值评分）:"),
    ("Qualitative risks (LLM extracted, not numerically scored):", "定性风险（由 LLM 提取，不参与数值评分）:"),
    ("Data limitations:", "数据限制:"),
    ("Status:", "状态:"),
    ("Minimum sample floor:", "最小样本门槛:"),
    ("per horizon", "每个周期"),
    ("Enrichment:", "数据增强:"),
    ("configured", "已配置"),
    ("not 已配置", "未配置"),
    ("not configured", "未配置"),
    ("unavailable", "不可用"),
    ("New V6 signals:", "新增 V6 信号:"),
    ("Skipped existing:", "跳过已存在信号:"),
    ("Skipped unusable:", "跳过不可用记录:"),
    ("New matured outcomes:", "新增已成熟结果:"),
    ("Not yet mature:", "尚未成熟结果:"),
    ("SQLite quick_check:", "SQLite 完整性检查:"),
    ("Generated by", "生成器:"),
    (" at ", "，时间: "),
    ("No V6 signals available.", "暂无可用的 V6 信号。"),
    ("SEC/FRED are evidence-only in V6.0. They do not change numeric scores until a historical mapping is validated.", "V6.0 中 SEC/FRED 仅作为证据与背景信息；在历史映射通过验证前，不会直接改变数值评分。"),
    ("V6 direction uses deterministic Trend, Momentum, Relative Strength and Market Regime features.", "V6 方向判断使用确定性的趋势、动量、相对强弱和市场状态因子。"),
    ("Opportunity/Quality/Risk and trade plan reuse the deterministic Alpha decision layer.", "机会/质量/风险评分以及交易计划复用确定性的 Alpha 决策层。"),
    ("Missing evidence lowers coverage instead of being replaced with a fake neutral 50.", "缺失证据会降低覆盖率，而不是用虚假的中性 50 分填充。"),
    ("AVOID means no position; it is evaluated as avoidance accuracy, never as an implicit short.", "回避（AVOID）表示不持仓；只统计回避准确率，绝不等同于隐式做空。"),
    ("Outcomes mature after 5/10/20 future trading bars, not calendar days.", "预测结果按未来 5/10/20 个交易日成熟，而不是按自然日。"),
    ("LLM prose has zero direct numeric influence on V6 scores.", "LLM 文本对 V6 数值评分没有直接影响。"),
    ("SEC/FRED enrichment is evidence-only until its scoring contribution is validated out-of-sample.", "SEC/FRED 数据在样本外验证其增益前仅作为证据，不直接进入评分。"),
    ("Trend ", "趋势 "),
    ("Momentum ", "动量 "),
    ("Volume ", "量能 "),
    ("Fundamental ", "基本面 "),
    ("Regime ", "市场状态 "),
)

_TABLE_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("| Rank | Symbol | Decision | Direction | Forecast | Opportunity | Quality | Risk | Evidence | LLM |", "| 排名 | 标的 | 决策 | 方向 | 预测分 | 机会分 | 质量分 | 风险分 | 证据 | LLM |"),
    ("| Horizon | N | Direction Hit | BUY N | BUY Hit | Avoid N | Avoid Hit | Forecast IC | Opportunity IC |", "| 周期 | 样本数 | 方向命中率 | 买入样本 | 买入命中率 | 回避样本 | 回避命中率 | 预测 IC | 机会 IC |"),
)

_TOKEN_MAP = {
    "BUY_SETUP": "买入准备",
    "WATCH": "观察",
    "WAIT": "等待",
    "AVOID": "回避",
    "bullish": "看多",
    "neutral": "中性",
    "bearish": "看空",
    "healthy": "正常",
    "fallback": "已回退",
    "degraded": "降级",
    "unknown": "未知",
    "missing": "缺失",
    "insufficient_data": "数据不足",
    "risk_on": "风险偏好开启",
    "risk_off": "风险偏好关闭",
    "broad": "广泛",
    "narrow": "狭窄",
}


def translate_v6_markdown_to_chinese(markdown: str) -> str:
    """Translate V6 human-facing Markdown labels without mutating data fields."""

    text = str(markdown or "")
    for old, new in _TABLE_REPLACEMENTS:
        text = text.replace(old, new)
    for old, new in _TEXT_REPLACEMENTS:
        text = text.replace(old, new)

    # Replace standalone operational tokens only.  Word boundaries avoid
    # rewriting symbols or arbitrary prose that merely contains the token.
    for token, translated in _TOKEN_MAP.items():
        text = re.sub(rf"(?<![A-Za-z0-9_]){re.escape(token)}(?![A-Za-z0-9_])", translated, text)

    return text


def _strip_v4_top_heading(markdown: str) -> str:
    lines = str(markdown or "").strip().splitlines()
    if lines and lines[0].lstrip().startswith("# "):
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines.pop(0)
    return "\n".join(lines).strip()


def build_unified_chinese_report(v6_markdown: str, v4_markdown: Optional[str] = None) -> str:
    """Return the one final Chinese daily email body.

    V6 remains the executive/risk layer at the top.  When the triggering V4
    artifact is available, its full detailed analysis is appended below so the
    previous V4 email loses no information even though V4 notification itself
    is disabled.
    """

    v6_chinese = translate_v6_markdown_to_chinese(v6_markdown).rstrip()
    v4_body = _strip_v4_top_heading(v4_markdown or "")
    if not v4_body:
        return v6_chinese + "\n"

    return (
        v6_chinese
        + "\n\n---\n\n"
        + "## 9. V4 AI 深度分析\n\n"
        + "> 以下内容来自同一次上游 V4 分析任务，保留原有行情、新闻、财务摘要、作战计划与信号归因；V6 位于邮件前半部分负责确定性评分、排序、风险与验证。\n\n"
        + v4_body
        + "\n"
    )
